.PHONY: clean All

All:
	@echo "----------Building project:[ data_struct - Debug ]----------"
	@"$(MAKE)" -f  "data_struct.mk"
clean:
	@echo "----------Cleaning project:[ data_struct - Debug ]----------"
	@"$(MAKE)" -f  "data_struct.mk" clean
